[options]
; Database
db_host = postgres
db_port = 5432
db_user = stroiuprav
db_password = False
db_name = stroiuprav
db_maxconn = 64

; Paths
addons_path = /opt/odoo/addons,/mnt/extra-addons
data_dir = /var/lib/odoo

; Network
proxy_mode = True
xmlrpc_port = 8069

; Workers
workers = 4
max_cron_threads = 2

; Memory limits
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648

; Time limits
limit_time_cpu = 600
limit_time_real = 1200
limit_time_real_cron = 3600

; Logging
log_level = info
logfile = /var/log/odoo/odoo-server.log
logrotate = True

; Security
list_db = False
admin_passwd = False
